language: node_js
node_js: lts/*
sudo: true
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
- yarn install
- add-apt-repository ppa:jonathonf/python-3.6 -y && apt-get update && apt-get install python3.6 && pip install --upgrade pip && pip install brotli
- pip install zopfli
script:
- yarn bundle:prod && yarn run start
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master